version: '3.8'
services:
  api:
    build: .
    container_name: nest_api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
